// Converted from Anchor 0.31 IDL to 0.28 format for @coral-xyz/anchor v0.28.0
// Source: packages/anchor/target/idl/pledge.json

export const IDL = {
  version: '0.1.0',
  name: 'pledge',
  instructions: [
    {
      name: 'createPledge',
      accounts: [
        { name: 'user', isMut: true, isSigner: true },
        { name: 'config', isMut: false, isSigner: false },
        { name: 'pledge', isMut: true, isSigner: false },
        { name: 'vault', isMut: true, isSigner: false },
        { name: 'userTokenAccount', isMut: true, isSigner: false },
        { name: 'mint', isMut: false, isSigner: false },
        { name: 'tokenProgram', isMut: false, isSigner: false },
        { name: 'associatedTokenProgram', isMut: false, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'stakeAmount', type: 'u64' },
        { name: 'deadline', type: 'i64' },
        { name: 'createdAt', type: 'i64' },
      ],
    },
    {
      name: 'editPledge',
      accounts: [
        { name: 'user', isMut: false, isSigner: true },
        { name: 'config', isMut: false, isSigner: false },
        { name: 'pledge', isMut: true, isSigner: false },
        { name: 'vault', isMut: true, isSigner: false },
        { name: 'treasuryTokenAccount', isMut: true, isSigner: false },
        { name: 'charityTokenAccount', isMut: true, isSigner: false },
        { name: 'tokenProgram', isMut: false, isSigner: false },
      ],
      args: [{ name: 'newDeadline', type: { option: 'i64' } }],
    },
    {
      name: 'reportCompletion',
      accounts: [
        { name: 'user', isMut: false, isSigner: true },
        { name: 'config', isMut: false, isSigner: false },
        { name: 'pledge', isMut: true, isSigner: false },
      ],
      args: [{ name: 'completionPercentage', type: 'u8' }],
    },
    {
      name: 'processCompletion',
      accounts: [
        { name: 'crank', isMut: false, isSigner: true },
        { name: 'config', isMut: false, isSigner: false },
        { name: 'pledge', isMut: true, isSigner: false },
        { name: 'vault', isMut: true, isSigner: false },
        { name: 'user', isMut: true, isSigner: false },
        { name: 'userTokenAccount', isMut: true, isSigner: false },
        { name: 'treasuryTokenAccount', isMut: true, isSigner: false },
        { name: 'charityTokenAccount', isMut: true, isSigner: false },
        { name: 'tokenProgram', isMut: false, isSigner: false },
      ],
      args: [],
    },
    {
      name: 'proposeAdminTransfer',
      accounts: [
        { name: 'admin', isMut: true, isSigner: true },
        { name: 'config', isMut: true, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
      ],
      args: [{ name: 'newAdmin', type: 'publicKey' }],
    },
    {
      name: 'acceptAdminTransfer',
      accounts: [
        { name: 'newAdmin', isMut: false, isSigner: true },
        { name: 'config', isMut: true, isSigner: false },
      ],
      args: [],
    },
  ],
  accounts: [
    {
      name: 'Pledge',
      type: {
        kind: 'struct',
        fields: [
          { name: 'user', type: 'publicKey' },
          { name: 'mint', type: 'publicKey' },
          { name: 'stakeAmount', type: 'u64' },
          { name: 'deadline', type: 'i64' },
          { name: 'status', type: { defined: 'PledgeStatus' } },
          { name: 'completionPercentage', type: { option: 'u8' } },
          { name: 'reportedAt', type: { option: 'i64' } },
          { name: 'createdAt', type: 'i64' },
          { name: 'bump', type: 'u8' },
          { name: 'vaultBump', type: 'u8' },
        ],
      },
    },
    {
      name: 'ProgramConfig',
      type: {
        kind: 'struct',
        fields: [
          { name: 'admin', type: 'publicKey' },
          { name: 'treasury', type: 'publicKey' },
          { name: 'charity', type: 'publicKey' },
          { name: 'treasurySplitBps', type: 'u16' },
          { name: 'partialFeeBps', type: 'u16' },
          { name: 'editPenaltyBps', type: 'u16' },
          { name: 'gracePeriodSeconds', type: 'i64' },
          { name: 'paused', type: 'bool' },
          { name: 'bump', type: 'u8' },
          { name: 'crankAuthority', type: 'publicKey' },
          { name: 'allowedMint', type: 'publicKey' },
          { name: 'pendingAdmin', type: { option: 'publicKey' } },
        ],
      },
    },
  ],
  types: [
    {
      name: 'PledgeStatus',
      type: {
        kind: 'enum',
        variants: [
          { name: 'Active' },
          { name: 'Reported' },
          { name: 'Completed' },
          { name: 'Forfeited' },
          { name: 'Cancelled' },
        ],
      },
    },
  ],
  errors: [
    { code: 6000, name: 'Unauthorized', msg: 'Unauthorized - not admin' },
    { code: 6001, name: 'NotPledgeOwner', msg: 'Unauthorized - not pledge owner' },
    { code: 6002, name: 'ProgramPaused', msg: 'Program is paused' },
    { code: 6003, name: 'InvalidTreasurySplit', msg: 'Invalid treasury split - must be <= 10000 bps' },
    { code: 6004, name: 'InvalidFee', msg: 'Invalid fee - must be <= 1000 bps (10%)' },
    { code: 6005, name: 'InvalidTimestamp', msg: 'Invalid timestamp - exceeds clock drift tolerance' },
    { code: 6006, name: 'InvalidDeadline', msg: 'Invalid deadline - must be in the future' },
    { code: 6007, name: 'InvalidStakeAmount', msg: 'Invalid stake amount - must be greater than 0' },
    { code: 6008, name: 'PledgeNotActive', msg: 'Pledge is not active' },
    { code: 6009, name: 'PledgeNotReported', msg: 'Pledge is not reported' },
    { code: 6010, name: 'DeadlineNotPassed', msg: 'Deadline has not passed yet' },
    { code: 6011, name: 'DeadlineAlreadyPassed', msg: 'Deadline has already passed' },
    { code: 6012, name: 'GracePeriodNotEnded', msg: 'Grace period has not ended' },
    { code: 6013, name: 'GracePeriodEnded', msg: 'Grace period has ended - cannot report' },
    { code: 6014, name: 'AlreadyReported', msg: 'Pledge already reported - use process_completion instead' },
    { code: 6015, name: 'InvalidCompletionPercentage', msg: 'Invalid completion percentage - must be 0-100' },
    { code: 6016, name: 'InvalidGracePeriod', msg: 'Invalid grace period - must be greater than zero' },
    { code: 6017, name: 'NotPendingAdmin', msg: 'Not the pending admin' },
    { code: 6018, name: 'NoPendingAdminTransfer', msg: 'No pending admin transfer' },
    { code: 6019, name: 'Overflow', msg: 'Numeric overflow' },
    { code: 6020, name: 'Underflow', msg: 'Numeric underflow' },
    { code: 6021, name: 'InvalidMint', msg: 'Invalid token mint' },
    { code: 6022, name: 'InvalidTokenAccountOwner', msg: 'Invalid token account owner' },
  ],
} as const;
