import {
  white,
  black,
  slateIndigo,
  warmCoral,
  blue,
  red,
  gray,
  lightTextSecondary,
  lightBorder,
  lightCardBackground,
  darkTextSecondary,
  darkBorder,
  darkCardBackground,
  statusCompleted,
  statusCompletedBg,
  statusForfeited,
  statusForfeitedBg,
  primaryAlpha10,
  primaryAlpha20,
  primaryAlpha40,
  iconOnPrimary,
  shadowColor,
} from './colors';

export const lightTheme = {
  colors: {
    background: white,
    text: black,
    textSecondary: lightTextSecondary,
    tint: blue,
    tabIconDefault: gray,
    primary: slateIndigo,
    success: warmCoral,
    error: red,
    border: lightBorder,
    separator: lightBorder,
    cardBackground: lightCardBackground,
    statusCompleted,
    statusCompletedBg,
    statusForfeited,
    statusForfeitedBg,
    primaryAlpha10,
    primaryAlpha20,
    primaryAlpha40,
    iconOnPrimary,
    shadowColor,
  },
};

export const darkTheme = {
  colors: {
    background: black,
    text: white,
    textSecondary: darkTextSecondary,
    tint: white,
    tabIconDefault: gray,
    primary: slateIndigo,
    success: warmCoral,
    error: red,
    border: darkBorder,
    separator: darkBorder,
    cardBackground: darkCardBackground,
    statusCompleted,
    statusCompletedBg,
    statusForfeited,
    statusForfeitedBg,
    primaryAlpha10,
    primaryAlpha20,
    primaryAlpha40,
    iconOnPrimary,
    shadowColor,
  },
};

export type AppTheme = typeof lightTheme;
